service: default
runtime: python39

basic_scaling:
    max_instances: 4
    idle_timeout: 10m

resources:
    cpu: 8
    memory_gb: 16
    disk_size_gb: 20

entrypoint: gunicorn -b 0.0.0.0:8080 main:server